Imports System.Data.SqlClient
Imports System.Security.Cryptography
Imports System.Text
Public Class GenHTMLChart
    Sub GenHTMLChartMain(ByRef DasaListP As DataTable)
        'Dim HIDUIDDateTime = UID + "_" + HID
        'HIDUIDDateTime = HIDUIDDateTime.Replace("/", "_").Replace("\", "_")
        'Dim fPath0 = "C:\Astro\Templates\" + HIDUIDDateTime + ".html"
        Dim fPath1 = "C:\Astro\Templates\Dasha.html"
        'If System.IO.File.Exists(fPath0) = True Then
        '    System.IO.File.Delete(fPath0)
        'End If
        If System.IO.File.Exists(fPath1) = True Then
            System.IO.File.Delete(fPath1)
        End If
        'Dim afile0 As New IO.StreamWriter(fPath0, True)
        Dim afile1 As New IO.StreamWriter(fPath1, True)
        'Dim Charttext = HTMLStringBuilder(HIDUIDDateTime, HID, UID, P_List, H_List, BirthLagna, BirthBhav, BirthSouth, DasaListP, personalDetails)
        Dim Dashatext = DashaStringBuilder(DasaListP)
        'afile0.WriteLine(Charttext)
        afile1.WriteLine(Dashatext)
        'afile0.Close()
        afile1.Close()
        'UpdateLink(HIDUIDDateTime, HID, UID)
    End Sub

    Function DashaStringBuilder(ByRef DasaListP As DataTable) As String
        Dim htmlBuilder As StringBuilder = New StringBuilder()
        Dim CD = DateTime.Now
        Dim StartIndex = 0
        For i = 0 To DasaListP.Rows.Count - 1

            Dim dt = DasaListP.Rows(i).ItemArray(5).ToString().Split(" :: ")(0).Replace("/", "-").Split("-")
            Dim DD = DateTime.Parse(dt(1) + "-" + dt(0) + "-" + dt(2))
            If CD <= DD Then
                StartIndex = i
                Exit For
            End If
        Next
        Dim EndIndex = 0
        CD = CD.AddYears(40)
        For i = 0 To DasaListP.Rows.Count - 1

            Dim dt = DasaListP.Rows(i).ItemArray(5).ToString().Split(" :: ")(0).Replace("/", "-").Split("-")
            Dim DD = DateTime.Parse(dt(1) + "-" + dt(0) + "-" + dt(2))
            If CD <= DD Then
                EndIndex = i
                Exit For
            End If
        Next
        If EndIndex = 0 Then
            EndIndex = DasaListP.Rows.Count
        End If
        htmlBuilder.Append(vbCrLf + "<!DOCTYPE html>")
        htmlBuilder.Append(vbCrLf + "<html lang='en'>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "<head>")
        htmlBuilder.Append(vbCrLf + "    <meta charset='utf-8' name='viewport' content='width=device-width initial-scale=0'>")
        htmlBuilder.Append(vbCrLf + "    <title>" + "personalDetails.NameoftheChartOwner" + " Dasha List</title>")
        htmlBuilder.Append(vbCrLf + "</head>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "<body>")
        htmlBuilder.Append(vbCrLf + "<h3 style='font-family: sans-serif;text-align: center;'>" + "personalDetails.NameoftheChartOwner" + "</h3>")
        htmlBuilder.Append(vbCrLf + "    <table width='100%' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td colspan='3' style='padding-left: 20px;'>")
        htmlBuilder.Append(vbCrLf + "                <p style='margin: 0;font-family: sans-serif;'><strong>D : Dasha, B : Bhukti, A : Antara</strong></p>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "        <tr>")
        htmlBuilder.Append(vbCrLf + "            <td style='width:30.35%;vertical-align: top;'>")
        htmlBuilder.Append(vbCrLf + "                <table width='100%' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <table style='margin:auto;border: 1px solid #b7b4b4;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;width: 400px;' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "                                <thead style='display:table;width: 400px;'>")
        htmlBuilder.Append(vbCrLf + "                                    <tr>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>D</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>B</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>A</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;border-right: 0;width: 200px;'>Closing Date & Time</th>")
        htmlBuilder.Append(vbCrLf + "                                    </tr>")
        htmlBuilder.Append(vbCrLf + "                                </thead>")
        htmlBuilder.Append(vbCrLf + "                                <tbody style='display:block;width: 400px;height: auto;'>")
        Dim OneThird As Integer = (EndIndex - StartIndex) * 0.3333333
        For i As Integer = StartIndex - 1 To (StartIndex + OneThird) - 1
            htmlBuilder.Append(vbCrLf + "                                    <tr>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(0) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(1) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(2) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;width: 200px;'>" + DasaListP.Rows(i).ItemArray(5) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                    <tr>")
        Next
        htmlBuilder.Append(vbCrLf + "                                </tbody>")
        htmlBuilder.Append(vbCrLf + "                            </table>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "            <td style='width:30.35%;vertical-align: top;'>")
        htmlBuilder.Append(vbCrLf + "                <table width='100%' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <table style='margin:auto;border: 1px solid #b7b4b4;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;width: 400px;' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "                                <thead style='display:table;width: 400px;'>")
        htmlBuilder.Append(vbCrLf + "                                    <tr>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>D</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>B</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>A</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;border-right: 0;width: 200px;'>Closing Date & Time</th>")
        htmlBuilder.Append(vbCrLf + "                                    </tr>")
        htmlBuilder.Append(vbCrLf + "                                </thead>")
        htmlBuilder.Append(vbCrLf + "                                <tbody style='display:block;width: 400px;height: auto;'>")
        htmlBuilder.Append(vbCrLf + "                                    <tr>")
        Dim TwoThird As Integer = (EndIndex - StartIndex) * 0.6666666
        For i As Integer = StartIndex + OneThird To (StartIndex + TwoThird) - 1
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(0) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(1) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(2) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;width: 200px;'>" + DasaListP.Rows(i).ItemArray(5) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                    </tr>")
        Next
        htmlBuilder.Append(vbCrLf + "                                </tbody>")
        htmlBuilder.Append(vbCrLf + "                            </table>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "            <td style='width:30.35%;vertical-align: top;'>")
        htmlBuilder.Append(vbCrLf + "                <table width='100%' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "                    <tr>")
        htmlBuilder.Append(vbCrLf + "                        <td>")
        htmlBuilder.Append(vbCrLf + "                            <table style='margin:auto;border: 1px solid #b7b4b4;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;width: 400px;' cellspacing='0' cellpadding='0'>")
        htmlBuilder.Append(vbCrLf + "                                <thead style='display:table;width: 400px;'>")
        htmlBuilder.Append(vbCrLf + "                                    <tr>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>D</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>B</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;width:66px;'>A</th>")
        htmlBuilder.Append(vbCrLf + "                                        <th style='border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;   border-bottom: 1px solid #b7b4b4;border-right: 1px solid #b7b4b4;border-right: 0;width: 200px;'>Closing Date & Time</th>")
        htmlBuilder.Append(vbCrLf + "                                    </tr>")
        htmlBuilder.Append(vbCrLf + "                                </thead>")
        htmlBuilder.Append(vbCrLf + "                                <tbody style='display:block;width: 400px;height:auto;'>")
        htmlBuilder.Append(vbCrLf + "                                    <tr>")
        For i As Integer = StartIndex + TwoThird To EndIndex - 1
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(0) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(1) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;border-right: 1px solid #b7b4b4;width:66px;'>" + DasaListP.Rows(i).ItemArray(2) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                        <td style='text-align:center;border-collapse: collapse;padding:5px 3px;color: #33334B;font-family: sans-serif;font-size: 11px;width: 200px;'>" + DasaListP.Rows(i).ItemArray(5) + "</td>")
            htmlBuilder.Append(vbCrLf + "                                    </tr>")
        Next
        htmlBuilder.Append(vbCrLf + "                                </tbody>")
        htmlBuilder.Append(vbCrLf + "                            </table>")
        htmlBuilder.Append(vbCrLf + "                        </td>")
        htmlBuilder.Append(vbCrLf + "                    </tr>")
        htmlBuilder.Append(vbCrLf + "                </table>")
        htmlBuilder.Append(vbCrLf + "            </td>")
        htmlBuilder.Append(vbCrLf + "        </tr>")
        htmlBuilder.Append(vbCrLf + "    </table>")
        htmlBuilder.Append(vbCrLf + "</body>")
        htmlBuilder.Append(vbCrLf + "")
        htmlBuilder.Append(vbCrLf + "</html>")
        Return htmlBuilder.ToString()
    End Function
    'Function HTMLStringBuilder(ByRef HIDUIDDateTime As String, ByRef HID As String, ByRef UID As String, ByRef P_List As String(), ByRef H_List As String(), ByRef BirthLagna As String(,), ByRef BirthBhav As String(,), ByRef BirthSouth As String(), ByRef DasaListP As DataTable, ByRef personalDetails As PersonalDetails) As String
    '    Dim htmlBuilder As StringBuilder = New StringBuilder()
    '    htmlBuilder.Append(vbCrLf + "<!DOCTYPE html>")
    '    htmlBuilder.Append(vbCrLf + "<html lang='en'>")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "<head>")
    '    htmlBuilder.Append(vbCrLf + "    <meta charset='utf-8' name='viewport' content='width=device-width initial-scale=0'>")
    '    htmlBuilder.Append(vbCrLf + "    <title>" + personalDetails.NameoftheChartOwner + " Chart</title>")
    '    htmlBuilder.Append(vbCrLf + "</head>")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "<body>")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table width='744'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width:65%'>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Name of the Chart Owner :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.NameoftheChartOwner + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Date of Birth :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.DateofBirth + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Place of Birth :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.PlaceofBirth + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Time of Birth(24 Hours) :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.TimeofBirth + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Latitude :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Latitude + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Longtitude :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Longitude + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Day of Birth :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.DayofBirth + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Rashi :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Rashi + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Star :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Star + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Sun Sign :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.SunSign + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Balance Dasa :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.BalanceDasa + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Planetary position</h3></td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table width='744' style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Planet</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Sign</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>D-M-S</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>RL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>STL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SSL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SukL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>PraL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Hse</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>D</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>PS</th>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    For i As Integer = 1 To 12
    '        htmlBuilder.Append(vbCrLf + "                    <tr>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(0) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(1) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(2) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(3) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(4) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(5) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(6) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(7) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(8) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(9) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(10) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + P_List(i).Split("|")(11) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    Next
    '
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>Cuspal position</h3></td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table width='744' style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Cusp</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>Sign</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>D-M-S</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>RL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>STL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SSL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>SukL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>PraL</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>%SArc</th>")
    '    htmlBuilder.Append(vbCrLf + "                        <th style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>%PArc</th>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    For i As Integer = 1 To 12
    '        htmlBuilder.Append(vbCrLf + "                    <tr>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(0) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(1) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(2) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(3) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(4) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(5) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(6) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(7) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(8) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(9) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                        <td style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + H_List(i).Split("|")(10) + "</td>")
    '        htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    Next
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>South Indian chart</h3>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table width='744' style='border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;font-weight: 700;'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-top:2px solid #ff00ff;border-left:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;'>" + If(BirthSouth(12) <> "", BirthSouth(12).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(12).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-top:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;'>" + If(BirthSouth(1) <> "", BirthSouth(1).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(1).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-top:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;'>" + If(BirthSouth(2) <> "", BirthSouth(2).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(2).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-top:2px solid #ff00ff;border-right:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;;font-weight: 700'>" + If(BirthSouth(3) <> "", BirthSouth(3).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(3).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-left:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;'>" + If(BirthSouth(11) <> "", BirthSouth(11).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(11).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;' rowspan='2' colspan='2'></td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-right:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;'>" + If(BirthSouth(4) <> "", BirthSouth(4).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(4).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-left:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + If(BirthSouth(10) <> "", BirthSouth(10).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(10).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-right:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>" + If(BirthSouth(5) <> "", BirthSouth(5).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(5).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-bottom: 2px solid #ff00ff;border-left:2px solid #ff00ff;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;'>" + If(BirthSouth(9) <> "", BirthSouth(9).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(9).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;border-bottom: 2px solid #ff00ff;'>" + If(BirthSouth(8) <> "", BirthSouth(8).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(8).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;border-bottom: 2px solid #ff00ff;'>" + If(BirthSouth(7) <> "", BirthSouth(7).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(7).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width: 25%;height: 100px;text-align: center;border: 2px solid #ff8c00;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;font-weight: 700;border-bottom: 2px solid #ff00ff;border-right:2px solid #ff00ff;'>" + If(BirthSouth(6) <> "", BirthSouth(6).Replace(vbCrLf, "<br>").Substring(0, BirthSouth(6).Replace(vbCrLf, "<br>").Length - 4), "") + "</td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 class='original-data' style='margin: 0 0 10px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'><u>Original data provided by the chart owner</u></h3>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table width='744' style='margin-bottom: 30px;'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width:65%'>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Date of Birth :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.OriginalDOBByChartOwner + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Place of Birth :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.OriginalPOBByChartOwner + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Time of Birth :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.OriginalTOBByChartOwner + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 class='original-data' style='margin-top: 40px;margin: 0 0 10px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'><u>Critical data given by chart owner</u></h3></td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table width='744'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td style='width:65%'>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Marriage :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.Marriage + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>First child :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.FirstChild + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Last call received :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.LastCallRecieved + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    <tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style=' margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 15px;'>Demise of relatives :</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                        <td>")
    '    htmlBuilder.Append(vbCrLf + "                            <p style='margin: 5px 0;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 14px;'>" + personalDetails.DemiseOfRelatives + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                        </td>")
    '    htmlBuilder.Append(vbCrLf + "                    </tr>")
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "    <table style='width:700px;margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;box-sizing: border-box;' cellspacing='0' cellpadding='0'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "             <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 style='margin: 0 0 20px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'>North Indian chart</h3>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <table  cellspacing='0' cellpadding='0' style='padding: 15px;border: 2px solid #08089a;'>")
    '    htmlBuilder.Append(vbCrLf + "                    <tbody>")
    '    htmlBuilder.Append(vbCrLf + "                        <tr>")
    '    htmlBuilder.Append(vbCrLf + "                            <td>")
    '    htmlBuilder.Append(vbCrLf + "                                <div style=' position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 2px solid blue;top: -15px;left: -15px;border-top: 0;border-left: 0;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 15px;width: 2px;background: blue;top: -15px;right: -1px;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;bottom: 0;right: -5px;font-weight:700;color:red;'>" + BirthLagna(1, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 49%;top: 30%;font-weight:700;color:red;'>" + BirthLagna(2, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 40%;top: 40%;font-weight:700;color:red;'>" + BirthLagna(3, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;left: 10%;transform: translateY(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(3, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 6%;left: 50%;transform: translateX(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(2, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;right: -29px;top: 50%;transform: translateY(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(1, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                    </svg>")
    '    htmlBuilder.Append(vbCrLf + "                                </div>")
    '    htmlBuilder.Append(vbCrLf + "                            </td>")
    '    htmlBuilder.Append(vbCrLf + "                            <td>")
    '    htmlBuilder.Append(vbCrLf + "                                <div style='position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 2px solid blue;top: -15px;right: -15px;border-top: 0;border-right: 0;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 2px;width: 15px;background: blue;bottom: -1px;right: -15px;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;bottom: -25px;left: 23px;font-weight:700;color:red;'>" + BirthLagna(10, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 49%;top: 30%;font-weight:700;color:red;'>" + BirthLagna(12, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 40%;top: 40%;font-weight:700;color:red;'>" + BirthLagna(11, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 6%;left: 50%;transform: translateX(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(12, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;right: 9%;transform: translateY(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(11, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;bottom: -22px;left: 50%;transform: translateX(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(10, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                    </svg>")
    '    htmlBuilder.Append(vbCrLf + "                                </div>")
    '    htmlBuilder.Append(vbCrLf + "                            </td>")
    '    htmlBuilder.Append(vbCrLf + "                        </tr>")
    '    htmlBuilder.Append(vbCrLf + "                        <tr>")
    '    htmlBuilder.Append(vbCrLf + "                            <td>")
    '    htmlBuilder.Append(vbCrLf + "                                <div style=' position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 2px solid blue;bottom: -15px;left: -15px;border-bottom: 0;border-left: 0;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 2px;width: 15px;background: blue;top: -1px;left: -15px;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 25px;top: -23px;font-weight:700;color:red;'>" + BirthLagna(4, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 40%;top: 40%;font-weight:700;color:red;'>" + BirthLagna(5, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: 48%;top: 48.4%;font-weight:700;color:red;'>" + BirthLagna(6, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;left: 10%;transform: translateY(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(5, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;bottom: 6%;left: 50%;transform: translateX(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(6, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: -13px;left: 50%;transform: translateX(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(4, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                    </svg>")
    '    htmlBuilder.Append(vbCrLf + "                                </div>")
    '    htmlBuilder.Append(vbCrLf + "                            </td>")
    '    htmlBuilder.Append(vbCrLf + "                            <td>")
    '    htmlBuilder.Append(vbCrLf + "                                <div style=' position: relative;width: 360px;height: 220px;border: 0px solid #FFF;'>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;width: 15px;height: 15px;border: 2px solid blue;bottom: -15px;right: -15px;border-bottom: 0;border-right: 0;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;height: 15px;width: 2px;background: blue;bottom: -15px;left: -1px;'></div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;left: -4px;top: 0;font-weight:700;color:red;'>" + BirthLagna(7, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 39%;top: 39%;font-weight:700;color:red;'>" + BirthLagna(9, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <p style='position: absolute;right: 48%;top: 48.4%;font-weight:700;color:red;'>" + BirthLagna(8, 0) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;bottom: 6%;left: 50%;transform: translateX(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(8, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;top: 50%;right: 9%;transform: translateY(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(9, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <div style='position: absolute;left: -29px;top: 50%;transform: translateY(-50%);'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <p style='font-weight: 700;margin: 0;font-size: 13px;text-align: center;'>" + BirthLagna(7, 1) + "</p>")
    '    htmlBuilder.Append(vbCrLf + "                                    </div>")
    '    htmlBuilder.Append(vbCrLf + "                                    <svg style='position: absolute;width: 100%;height: 100%;' viewBox='0 0 50 50' preserveAspectRatio='none'>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='0' x2='50' y2='50' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                        <line x1='0' y1='50' x2='50' y2='0' stroke='red' stroke-width='0.3'></line>")
    '    htmlBuilder.Append(vbCrLf + "                                    </svg>")
    '    htmlBuilder.Append(vbCrLf + "                                </div>")
    '    htmlBuilder.Append(vbCrLf + "                            </td>")
    '    htmlBuilder.Append(vbCrLf + "                        </tr>")
    '    htmlBuilder.Append(vbCrLf + "                    </tbody>")
    '    htmlBuilder.Append(vbCrLf + "                </table>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "    <table style='margin: 10px auto 20px;padding: 40px 30px;box-shadow: 0 3px 20px 0px #E1DAD1;border-radius: 8px;'>")
    '    htmlBuilder.Append(vbCrLf + "        <tr>")
    '    htmlBuilder.Append(vbCrLf + "            <td>")
    '    htmlBuilder.Append(vbCrLf + "                <h3 class='box-head' style='margin: 0 0 0px;color: #33334B;font-family: sans-serif;font-weight: 600;font-size: 18px;'><a href='http://49.50.103.132/letterhead/templates/" + HIDUIDDateTime + "_Dasha.html' target='_blank'>Dasa listing</a></h3>")
    '    htmlBuilder.Append(vbCrLf + "            </td>")
    '    htmlBuilder.Append(vbCrLf + "        </tr>")
    '    'htmlBuilder.Append(vbCrLf + "        <tr>")
    '    'htmlBuilder.Append(vbCrLf + "            <td>")
    '    'htmlBuilder.Append(vbCrLf + "                <table width='744' style='table-layout:fixed;margin:auto;border: 1px solid #ddd;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;'>")
    '    'htmlBuilder.Append(vbCrLf + "                    <thead style='display:table;width:calc(744px - 20px);'>")
    '    'htmlBuilder.Append(vbCrLf + "                        <tr>")
    '    'htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 120.66px;'>D</th>")
    '    'htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 120.66px;'>B</th>")
    '    'htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 120.66px;'>A</th>")
    '    'htmlBuilder.Append(vbCrLf + "                            <th style='border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;   border-bottom: 1px solid #ddd;border-right: 1px solid #ddd;width: 361.98px;border-right: 0;'>Closing Date & Time</th>")
    '    'htmlBuilder.Append(vbCrLf + "                        </tr>")
    '    'htmlBuilder.Append(vbCrLf + "                    </thead>")
    '    'htmlBuilder.Append(vbCrLf + "                    <tbody style='height:300px;overflow-x:hidden;display:block;width:100%;'>")
    '    'For i As Integer = 0 To DasaListP.Rows.Count - 1
    '    '    htmlBuilder.Append(vbCrLf + "                        <tr>")
    '    '    htmlBuilder.Append(vbCrLf + "                            <td style='text-align:center; width: 120.66px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(0) + "</td>")
    '    '    htmlBuilder.Append(vbCrLf + "                            <td style='text-align:center; width: 120.66px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(1) + "</td>")
    '    '    htmlBuilder.Append(vbCrLf + "                            <td style='text-align:center; width: 120.66px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(2) + "</td>")
    '    '    htmlBuilder.Append(vbCrLf + "                            <td style='text-align:center; width: 361.98px;border-collapse: collapse;padding: 8px;color: #33334B;font-family: sans-serif;font-size: 14px;border-right: 1px solid #ddd;'>" + DasaListP.Rows(i).ItemArray(5) + "</td>")
    '    '    htmlBuilder.Append(vbCrLf + "                        </tr>")
    '    'Next
    '    'htmlBuilder.Append(vbCrLf + "                    </tbody>")
    '    'htmlBuilder.Append(vbCrLf + "                </table>")
    '    'htmlBuilder.Append(vbCrLf + "            </td>")
    '    'htmlBuilder.Append(vbCrLf + "        </tr>")
    '    htmlBuilder.Append(vbCrLf + "    </table>")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "</body>")
    '    htmlBuilder.Append(vbCrLf + "")
    '    htmlBuilder.Append(vbCrLf + "</html>")
    '    Return htmlBuilder.ToString()
    'End Function
    Public Function Encrypt(ByVal input As String, ByVal key As String) As String
        Dim inputArray As Byte() = UTF8Encoding.UTF8.GetBytes(input)
        Dim tripleDES As TripleDESCryptoServiceProvider = New TripleDESCryptoServiceProvider()
        tripleDES.Key = UTF8Encoding.UTF8.GetBytes(key)
        tripleDES.Mode = CipherMode.ECB
        tripleDES.Padding = PaddingMode.PKCS7
        Dim cTransform As ICryptoTransform = tripleDES.CreateEncryptor()
        Dim resultArray As Byte() = cTransform.TransformFinalBlock(inputArray, 0, inputArray.Length)
        tripleDES.Clear()
        Return Convert.ToBase64String(resultArray, 0, resultArray.Length)
    End Function
    Public Function Decrypt(ByVal input As String, ByVal key As String) As String
        Dim inputArray As Byte() = Convert.FromBase64String(input)
        Dim tripleDES As TripleDESCryptoServiceProvider = New TripleDESCryptoServiceProvider()
        tripleDES.Key = UTF8Encoding.UTF8.GetBytes(key)
        tripleDES.Mode = CipherMode.ECB
        tripleDES.Padding = PaddingMode.PKCS7
        Dim cTransform As ICryptoTransform = tripleDES.CreateDecryptor()
        Dim resultArray As Byte() = cTransform.TransformFinalBlock(inputArray, 0, inputArray.Length)
        tripleDES.Clear()
        Return UTF8Encoding.UTF8.GetString(resultArray)
    End Function
    'Sub UpdateLink(ByRef linkCode As String, ByRef HID As String, ByRef UID As String)
    '    Dim con As New SqlConnection
    '    Dim cmd As New SqlCommand
    '    Try
    '        con.ConnectionString = Connstr.connstr
    '        con.Open()
    '        cmd.Connection = con
    '        cmd.CommandText = $"UPDATE ASTROLOGYSOFTWARE_DB.DBO.HMAIN
    '                                SET HPDF = 'http://49.50.103.132/letterhead/templates/" + linkCode + ".html' 
    '                                WHERE HUSERID = '" + UID + "' AND HID = '" + HID + "'"
    '        cmd.ExecuteNonQuery()
    '    Catch ex As Exception
    '        Dim strFile As String = String.Format("C:\Astro\ServiceLogs\ChartGeneration\ErrorLog.txt")
    '        IO.File.AppendAllText(strFile, String.Format(vbCrLf + "Error Occured at-- {0}{1}{2}", Environment.NewLine + DateTime.Now, Environment.NewLine, ex.Message + vbCrLf + ex.StackTrace))
    '    Finally
    '        con.Close()
    '    End Try
    'End Sub
End Class